# Generated by Django 2.0.4 on 2020-03-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='dlugiopis',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='krotkiopis',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
