# Generated by Django 2.0.4 on 2020-03-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_auto_20200314_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='image',
        ),
    ]
