# Generated by Django 2.0.4 on 2020-03-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_remove_produkty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
